name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Total Security Issues
        run: |
              length=$(cat snyk.sarif | jq '.runs[0].results | length')
              echo "RESULTS_LENGTH=$length" >> $GITHUB_ENV
      - name: High
        run: |
              high=$(cat snyk.sarif | jq '.runs[0].results | map(select(.level == "error")) | length')
              echo "RESULTS_HIGH=$high" >> $GITHUB_ENV
      - name: Medium
        run: |
              medium=$(cat snyk.sarif | jq '.runs[0].results | map(select(.level == "warning")) | length')
              echo "RESULTS_MEDIUM=$medium" >> $GITHUB_ENV
      - name: Low
        run: |
              low=$(cat snyk.sarif | jq '.runs[0].results | map(select(.level == "note")) | length')
              echo "RESULTS_LOW=$low" >> $GITHUB_ENV
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
                {
                   "text": "*The Snyk scan result for repo , snykgoof, is : ${{ job.status }}* \n*Number of vulnerabilities : ${{ env.RESULTS_LENGTH }}* \n*High : ${{ env.RESULTS_HIGH }}* \n*Medium : ${{ env.RESULTS_MEDIUM }}* \n*Low : ${{ env.RESULTS_LOW }}* \n*Detail*: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
