name: Snyk Scan and Store Results in DynamoDB

on:
  push:
    branches:
      - main

jobs:
  Security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --sarif-file-output=snyk-results.sarif

    - name: Parse Snyk results
      id: parse-results
      run: |
        critical=$(jq '[.runs[].results[] | select(.level == "error" and .properties.severity == "critical")] | length' snyk-results.sarif)
        high=$(jq '[.runs[].results[] | select(.level == "error" and .properties.severity == "high")] | length' snyk-results.sarif)
        medium=$(jq '[.runs[].results[] | select(.level == "warning" and .properties.severity == "medium")] | length' snyk-results.sarif)
        low=$(jq '[.runs[].results[] | select(.level == "note" and .properties.severity == "low")] | length' snyk-results.sarif)
        echo "Critical: $critical"
        echo "High: $high"
        echo "Medium: $medium"
        echo "Low: $low"
        echo "::set-output name=critical::$critical"
        echo "::set-output name=high::$high"
        echo "::set-output name=medium::$medium"
        echo "::set-output name=low::$low"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Send results to DynamoDB
      run: |
        response=$(aws dynamodb put-item \
          --table-name snyk \
          --item '{
            "id": {"S": "'"$(date +%s)"'"},
            "critical": {"N": "'"${{ steps.parse-results.outputs.critical }}"'"},
            "high": {"N": "'"${{ steps.parse-results.outputs.high }}"'"},
            "medium": {"N": "'"${{ steps.parse-results.outputs.medium }}"'"},
            "low": {"N": "'"${{ steps.parse-results.outputs.low }}"'"}
          }')
        echo "DynamoDB put-item response: $response"
    - name: Verify DynamoDB entry
      run: |
        aws dynamodb scan --table-name snyk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
