name: Snyk Scan and Store Results in DynamoDB

on:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --json > snyk-results.json

    - name: Parse Snyk results
      id: parse-results
      run: |
        critical=$(jq '.vulnerabilities | map(select(.severity == "critical")) | length' snyk-results.json)
        high=$(jq '.vulnerabilities | map(select(.severity == "high")) | length' snyk-results.json)
        medium=$(jq '.vulnerabilities | map(select(.severity == "medium")) | length' snyk-results.json)
        low=$(jq '.vulnerabilities | map(select(.severity == "low")) | length' snyk-results.json)
        echo "::set-output name=critical::$critical"
        echo "::set-output name=high::$high"
        echo "::set-output name=medium::$medium"
        echo "::set-output name=low::$low"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Send results to DynamoDB
      run: |
        aws dynamodb put-item \
          --table-name snyk \
          --item '{
            "id": {"S": "'"$(date +%s)"'"},
            "critical": {"N": "'"${{ steps.parse-results.outputs.critical }}"'"},
            "high": {"N": "'"${{ steps.parse-results.outputs.high }}"'"},
            "medium": {"N": "'"${{ steps.parse-results.outputs.medium }}"'"},
            "low": {"N": "'"${{ steps.parse-results.outputs.low }}"'"}
          }'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
