name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif
      - name: Send results to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_MESSAGE: |
          SnykGoof Vulnerabilities:
          Total Vulnerabilities: ${{ env.SNYK_TOTAL }}
          High: ${{ env.SNYK_HIGH }}
          Medium: ${{ env.SNYK_MEDIUM }}
          Low: ${{ env.SNYK_LOW }}
      - name: Install boto3
        run: |
          python -m pip install boto3
      - name: Upload results to DynamoDB
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          DYNAMODB_TABLE_NAME: "snyk"
        run: |
          python .github/workflows/upload_to_dynamodb.py snyk.sarif
      
